puts " The students of Villian Academy"
puts "----------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of thr West"
puts "Terminator"
puts "The Joker"
puts "Joffery Baratheon"
puts "Norman Bates"